/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BatDongSan;
import model.TaiKhoan;
import service.impl.BatDongSanService;

/**
 *
 * @author son45
 */
public class Detail extends javax.swing.JFrame {

    private List<BatDongSan> listBatDongSan;
    private List<String> listLoaiBDS;
    private List<String> listCSH;
    private List<String> listVP;
    private List<String> listTP;
    private DefaultTableModel dtm;
    private DefaultComboBoxModel dcbm;
    private BatDongSanService service;
    private TaiKhoan check;
    private BatDongSan bds;
    private Search s;

    /**
     * Creates new form Detail
     */
    public Detail(BatDongSan bds, TaiKhoan check) {
        initComponents();
        this.check = check;
        this.bds = bds;
        dtm = new DefaultTableModel();
        service = new BatDongSanService();
        listBatDongSan = new ArrayList<>();
        listBatDongSan = service.getData();
        s = new Search(check);
        loadListBDS();
        loadCSH();
        loadVP();
        loadTP();
        fill(0);
        txtMa.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        txtQuan = new javax.swing.JTextField();
        txtDienTich = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        cbxChuSoHuu = new javax.swing.JComboBox<>();
        cbxVanPhong = new javax.swing.JComboBox<>();
        cbxThanhPho = new javax.swing.JComboBox<>();
        cbxLoai = new javax.swing.JComboBox<>();
        txtMa = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Detail BÐS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSua.setBackground(new java.awt.Color(51, 51, 51));
        btnSua.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Tools_35px_1.png"))); // NOI18N
        btnSua.setText("Sua");
        btnSua.setBorder(null);
        btnSua.setPreferredSize(new java.awt.Dimension(169, 35));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(51, 51, 51));
        btnXoa.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_minus_35px.png"))); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.setBorder(null);
        btnXoa.setPreferredSize(new java.awt.Dimension(169, 35));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Thong tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(627, 242));

        jLabel62.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Id CSH:");

        jLabel63.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Id VP:");

        jLabel64.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Quan:");

        jLabel65.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Thanh pho:");

        jLabel66.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Loai:");

        jLabel67.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Dien tich:");

        jLabel68.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Dia chi:");

        txtQuan.setBackground(new java.awt.Color(51, 51, 51));
        txtQuan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtQuan.setForeground(new java.awt.Color(255, 255, 255));
        txtQuan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        txtDienTich.setBackground(new java.awt.Color(51, 51, 51));
        txtDienTich.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtDienTich.setForeground(new java.awt.Color(255, 255, 255));
        txtDienTich.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtDienTich.setPreferredSize(new java.awt.Dimension(198, 23));

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane8.setViewportView(txtDiaChi);

        cbxChuSoHuu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxChuSoHuu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxChuSoHuu.setPreferredSize(new java.awt.Dimension(198, 23));

        cbxVanPhong.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxVanPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxVanPhong.setPreferredSize(new java.awt.Dimension(198, 23));

        cbxThanhPho.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxThanhPho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxThanhPho.setPreferredSize(new java.awt.Dimension(198, 23));

        cbxLoai.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxLoai.setPreferredSize(new java.awt.Dimension(198, 23));

        txtMa.setBackground(new java.awt.Color(51, 51, 51));
        txtMa.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtMa.setForeground(new java.awt.Color(255, 255, 255));
        txtMa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtMa.setPreferredSize(new java.awt.Dimension(198, 23));

        jLabel69.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Ma:");

        jLabel70.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Giá");

        txtGia.setBackground(new java.awt.Color(51, 51, 51));
        txtGia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtGia.setForeground(new java.awt.Color(255, 255, 255));
        txtGia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtGia.setPreferredSize(new java.awt.Dimension(198, 23));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66)
                            .addComponent(jLabel69)
                            .addComponent(jLabel64))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuan)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel68))
                .addGap(50, 50, 50)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel65)
                    .addComponent(jLabel67)
                    .addComponent(jLabel62)
                    .addComponent(jLabel70)
                    .addComponent(jLabel63))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxVanPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbxChuSoHuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxThanhPho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDienTich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxChuSoHuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel62))
                            .addGap(0, 0, 0))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel67)
                                .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, 0)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel70)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel63)
                                    .addComponent(cbxVanPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel66)
                                    .addComponent(cbxThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel65))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel68))))
                        .addContainerGap())))
        );

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_return_35px.png"))); // NOI18N
        jButton4.setText("Quay Lai");
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(169, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel6.setText("Detail BÐS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_view_details_42px.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_view_details_42px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        boolean flag = myValidate();
        if (flag) {
            int chu = 0;
            if (cbxChuSoHuu.getSelectedIndex() == 0) {
                chu = 1;
            } else if (cbxChuSoHuu.getSelectedIndex() == 1) {
                chu = 2;
            } else if (cbxChuSoHuu.getSelectedIndex() == 2) {
                chu = 3;
            } else if (cbxChuSoHuu.getSelectedIndex() == 3) {
                chu = 4;
            } else {
                chu = 5;
            }
            int vanPhong = 0;
            if (cbxVanPhong.getSelectedIndex() == 0) {
                vanPhong = 1;
            } else if (cbxVanPhong.getSelectedIndex() == 1) {
                vanPhong = 2;
            } else {
                vanPhong = 3;
            }
            String ma = txtMa.getText();
            String diaChi = txtDiaChi.getText();
            String quan = txtQuan.getText();
            String thanhPho = (String) cbxThanhPho.getSelectedItem();
            String loai = (String) cbxLoai.getSelectedItem();
            int dien = Integer.valueOf(txtDienTich.getText());
            int gia = Integer.valueOf(txtGia.getText());
            BatDongSan bds = new BatDongSan(0, chu, vanPhong, ma, diaChi, quan, thanhPho, loai, dien, gia);
            boolean check = service.updateById(ma, bds);
            if (check) {
                showData(listBatDongSan = service.getData());
                JOptionPane.showMessageDialog(this, "Sửa Thành Công");
                this.dispose();
                s.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Thất bại");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maBDS = txtMa.getText();
        boolean delete = service.removeById(maBDS);
        if (delete) {
            JOptionPane.showConfirmDialog(this, "Xóa Thành Công");
            showData(listBatDongSan = service.getData());
            this.dispose();
            s.setVisible(true);
        } else {
            JOptionPane.showConfirmDialog(this, "Xóa Thất bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        s.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    public void showData(List<BatDongSan> list) {
        dtm.setRowCount(0);
        for (BatDongSan bds : list) {
            dtm.addRow(bds.toshowData());
        }
    }

    public void loadListBDS() {
        listLoaiBDS = new ArrayList<>();
        cbxLoai.setModel(dcbm = new DefaultComboBoxModel());
        listLoaiBDS.add("Đất thổ cư");
        listLoaiBDS.add("Đất nông nghiệp");
        listLoaiBDS.add("Đất lâm nghiệp");
        listLoaiBDS.add("Đất quy hoạch");
        dcbm.addAll(listLoaiBDS);
        cbxLoai.setSelectedIndex(0);
    }

    public void loadCSH() {
        listCSH = new ArrayList<>();
        cbxChuSoHuu.setModel(dcbm = new DefaultComboBoxModel());
        listCSH.add("Nguyễn Thanh Đức");
        listCSH.add("Nguyễn Thanh Tuấn");
        listCSH.add("Nguyễn Thanh Hiệu");
        listCSH.add("Nguyễn Thanh Nam");
        listCSH.add("Nguyễn Thanh Tùng");
        dcbm.addAll(listCSH);
        cbxChuSoHuu.setSelectedIndex(0);
    }

    public void loadVP() {
        listVP = new ArrayList();
        cbxVanPhong.setModel(dcbm = new DefaultComboBoxModel());
        listVP.add("Bất động sản Thành Hưng");
        listVP.add("Bất động sản Nam Hưng");
        listVP.add("Bất động sản Tuấn hưng");
        dcbm.addAll(listVP);
        cbxVanPhong.setSelectedIndex(0);
    }

    public void loadTP() {
        listTP = new ArrayList<>();
        cbxThanhPho.setModel(dcbm = new DefaultComboBoxModel());
        listTP.add("Hà Nội");
        listTP.add("Hồ Chí Minh");
        dcbm.addAll(listTP);
        cbxThanhPho.setSelectedIndex(0);
    }

    public void fill(int index) {
        String check = "";
        if (bds.getChuSoHuu() == 1) {
            check = "Nguyễn Thanh Đức";
        } else if (bds.getChuSoHuu() == 2) {
            check = "Nguyễn Thanh Tuấn";
        } else if (bds.getChuSoHuu() == 3) {
            check = "Nguyễn Thanh Hiệu";
        } else if (bds.getChuSoHuu() == 4) {
            check = "Nguyễn Thanh Nam";
        } else {
            check = "Nguyễn Thanh Tùng";
        }
        String check1 = "";
        if (bds.getVanPhong() == 1) {
            check1 = "Bất động sản Thành Hưng";
        } else if (bds.getVanPhong() == 2) {
            check1 = "Bất động sản Nam Hưng";
        } else {
            check1 = "Bất động sản Tuấn Hưng";
        }
        txtMa.setText(bds.getMa());
        txtDiaChi.setText(bds.getDiaChi());
        txtDienTich.setText(bds.getDienTich() + "");
        txtQuan.setText(bds.getQuan());
        cbxLoai.setSelectedItem(bds.getLoai());
        cbxChuSoHuu.setSelectedItem(check);
        cbxVanPhong.setSelectedItem(check1);
        cbxThanhPho.setSelectedItem(bds.getThanhPho());
        txtGia.setText(bds.getGia() + "");
    }

    public boolean myValidate() {
        boolean flag = false;
        int chon = 0;
        for (int i = 0; i < listBatDongSan.size(); i++) {
            if (listBatDongSan.get(i).equals(txtMa)) {
                chon++;
            }
        }
        if (txtMa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (txtQuan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (txtDiaChi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (txtDienTich.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (txtGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (!txtGia.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(rootPane, "giá và diện tích phải là số");
        } else if (!txtDienTich.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(rootPane, "giá và diện tích phải là số");
        } else if (chon > 0) {
            JOptionPane.showMessageDialog(rootPane, "không được nhập trùng mã");
        } else {
            flag = true;
        }
        return flag;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Detail().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxChuSoHuu;
    private javax.swing.JComboBox<String> cbxLoai;
    private javax.swing.JComboBox<String> cbxThanhPho;
    private javax.swing.JComboBox<String> cbxVanPhong;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtDienTich;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtQuan;
    // End of variables declaration//GEN-END:variables
}
