/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BatDongSan;
import model.TaiKhoan;
import service.impl.BatDongSanService;

/**
 *
 * @author Admin
 */
public class QuanLyBDS extends javax.swing.JFrame {

    private List<BatDongSan> listBatDongSan;
    private List<String> listLoaiBDS;
    private List<String> listCSH;
    private List<String> listVP;
    private List<String> listTP;
    private List<String> listSort;
    private List<String> listChieu = new ArrayList<>();
    private DefaultTableModel dtm;
    private DefaultComboBoxModel dcbm;
    private BatDongSanService service;
    private TaiKhoan check;

    /**
     * Creates new form QuanLyBDS
     */
    public QuanLyBDS(TaiKhoan check) {
        initComponents();
        this.check = check;
        service = new BatDongSanService();
        listBatDongSan = new ArrayList<>();
        listBatDongSan = service.getData();
        tblHienThi.setModel(dtm = new DefaultTableModel());
        loadListBDS();
        loadCSH();
        loadVP();
        loadTP();
        loadSort();
        loadChieu();
        String[] header = {"chủ sở hữu", "văn phòng", "mã", "địa chỉ", "quận", "thành phố", "Loại", "diện tích", "giá"};
        dtm.setColumnIdentifiers(header);
        showData(listBatDongSan);
        fill(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbxSapXep = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxChieu = new javax.swing.JComboBox<>();
        btnSua = new javax.swing.JButton();
        btnClearForm = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtQuan = new javax.swing.JTextField();
        txtDienTich = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        cbxChuSoHuu = new javax.swing.JComboBox<>();
        cbxVanPhong = new javax.swing.JComboBox<>();
        cbxThanhPho = new javax.swing.JComboBox<>();
        cbxLoai = new javax.swing.JComboBox<>();
        txtMa = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quan Ly BÐS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Quản Lý Bất Động Sản");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Chuc Nang", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(378, 244));

        btnThem.setBackground(new java.awt.Color(153, 153, 153));
        btnThem.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Plus_35px_1.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.setPreferredSize(new java.awt.Dimension(160, 35));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sắp xếp theo:");

        cbxSapXep.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSapXep.setPreferredSize(new java.awt.Dimension(254, 22));
        cbxSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSapXepActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chiều:");

        cbxChieu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxChieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxChieu.setPreferredSize(new java.awt.Dimension(254, 22));
        cbxChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxChieuActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(153, 153, 153));
        btnSua.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Tools_35px_1.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.setPreferredSize(new java.awt.Dimension(160, 35));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnClearForm.setBackground(new java.awt.Color(153, 153, 153));
        btnClearForm.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnClearForm.setForeground(new java.awt.Color(255, 255, 255));
        btnClearForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reset_35px.png"))); // NOI18N
        btnClearForm.setText("Đặt lại");
        btnClearForm.setBorder(null);
        btnClearForm.setPreferredSize(new java.awt.Dimension(160, 35));
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(153, 153, 153));
        btnXoa.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_minus_35px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(null);
        btnXoa.setPreferredSize(new java.awt.Dimension(160, 35));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(153, 153, 153));
        btnThoat.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_return_35px.png"))); // NOI18N
        btnThoat.setText("Quay lại");
        btnThoat.setBorder(null);
        btnThoat.setPreferredSize(new java.awt.Dimension(160, 35));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(cbxSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "Thong tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(627, 244));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Chủ sở hữu:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Văn phòng:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quận:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thành phố:");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Loại:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Diện tích:");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Địa chỉ:");

        txtQuan.setBackground(new java.awt.Color(51, 51, 51));
        txtQuan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtQuan.setForeground(new java.awt.Color(255, 255, 255));
        txtQuan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtQuan.setPreferredSize(new java.awt.Dimension(198, 22));

        txtDienTich.setBackground(new java.awt.Color(51, 51, 51));
        txtDienTich.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtDienTich.setForeground(new java.awt.Color(255, 255, 255));
        txtDienTich.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtDienTich.setPreferredSize(new java.awt.Dimension(198, 22));

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        cbxChuSoHuu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxChuSoHuu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxChuSoHuu.setPreferredSize(new java.awt.Dimension(198, 22));

        cbxVanPhong.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxVanPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxVanPhong.setPreferredSize(new java.awt.Dimension(198, 22));

        cbxThanhPho.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxThanhPho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxThanhPho.setPreferredSize(new java.awt.Dimension(198, 22));

        cbxLoai.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxLoai.setPreferredSize(new java.awt.Dimension(198, 22));

        txtMa.setBackground(new java.awt.Color(51, 51, 51));
        txtMa.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtMa.setForeground(new java.awt.Color(255, 255, 255));
        txtMa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtMa.setPreferredSize(new java.awt.Dimension(198, 22));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Mã:");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Giá:");

        txtGia.setBackground(new java.awt.Color(51, 51, 51));
        txtGia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtGia.setForeground(new java.awt.Color(255, 255, 255));
        txtGia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtGia.setPreferredSize(new java.awt.Dimension(198, 22));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel19)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxVanPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(cbxChuSoHuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxThanhPho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDienTich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxChuSoHuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addGap(145, 145, 145))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(cbxVanPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cbxThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addContainerGap())))
        );

        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHienThiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHienThi);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_real_estate_50px.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_real_estate_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel13)
                        .addGap(184, 184, 184)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel15)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String ma = txtMa.getText();
        boolean check = service.removeById(ma);
        if (check) {
            JOptionPane.showMessageDialog(this, "xóa thành công");
        } else {
            JOptionPane.showMessageDialog(this, "xóa không thành công");
        }
        showData(listBatDongSan = service.getData());
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TrangChu c = new TrangChu(check);
        c.setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHienThiMouseClicked
        // TODO add your handling code here:
        int index = tblHienThi.getSelectedRow();
        fill(index);
        txtMa.setEnabled(false);
    }//GEN-LAST:event_tblHienThiMouseClicked

    private void cbxSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSapXepActionPerformed
        // TODO add your handling code here:
        String loai = (String) cbxSapXep.getSelectedItem();
        String key = (String) cbxChieu.getSelectedItem();
        List<BatDongSan> list = service.sortBy(loai, key);
        showData(list);
    }//GEN-LAST:event_cbxSapXepActionPerformed

    private void cbxChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxChieuActionPerformed
        // TODO add your handling code here:
        String loai = (String) cbxSapXep.getSelectedItem();
        String key = (String) cbxChieu.getSelectedItem();
        List<BatDongSan> list = service.sortBy(loai, key);
        showData(list);
    }//GEN-LAST:event_cbxChieuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        boolean flag = myValidate();
        if (flag) {
            int chu = 0;
            if (cbxChuSoHuu.getSelectedIndex() == 0) {
                chu = 1;
            } else if (cbxChuSoHuu.getSelectedIndex() == 1) {
                chu = 2;
            } else if (cbxChuSoHuu.getSelectedIndex() == 2) {
                chu = 3;
            } else if (cbxChuSoHuu.getSelectedIndex() == 3) {
                chu = 4;
            } else {
                chu = 5;
            }
            int vanPhong = 0;
            if (cbxVanPhong.getSelectedIndex() == 0) {
                vanPhong = 1;
            } else if (cbxVanPhong.getSelectedIndex() == 1) {
                vanPhong = 2;
            } else {
                vanPhong = 3;
            }
            String ma = txtMa.getText();
            String diaChi = txtDiaChi.getText();
            String quan = txtQuan.getText();
            String thanhPho = (String) cbxThanhPho.getSelectedItem();
            String loai = (String) cbxLoai.getSelectedItem();
            int dien = Integer.valueOf(txtDienTich.getText());
            int gia = Integer.valueOf(txtGia.getText());
            BatDongSan bds = new BatDongSan(0, chu, vanPhong, ma, diaChi, quan, thanhPho, loai, dien, gia);
            boolean check = service.add(bds);
            if (check) {
                showData(listBatDongSan = service.getData());
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Thất bại");
            }
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        txtMa.setEnabled(true);
        txtDiaChi.setText("");
        txtDienTich.setText("");
        txtGia.setText("");
        txtMa.setText("");
        txtQuan.setText("");
        cbxChieu.setSelectedIndex(0);
        cbxChuSoHuu.setSelectedIndex(0);
        cbxLoai.setSelectedIndex(0);
        cbxSapXep.setSelectedIndex(0);
        cbxThanhPho.setSelectedIndex(0);
        cbxVanPhong.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearFormActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        boolean flag = myValidate();
        if (flag) {
            int chu = 0;
            if (cbxChuSoHuu.getSelectedIndex() == 0) {
                chu = 1;
            } else if (cbxChuSoHuu.getSelectedIndex() == 1) {
                chu = 2;
            } else if (cbxChuSoHuu.getSelectedIndex() == 2) {
                chu = 3;
            } else if (cbxChuSoHuu.getSelectedIndex() == 3) {
                chu = 4;
            } else {
                chu = 5;
            }
            int vanPhong = 0;
            if (cbxVanPhong.getSelectedIndex() == 0) {
                vanPhong = 1;
            } else if (cbxVanPhong.getSelectedIndex() == 1) {
                vanPhong = 2;
            } else {
                vanPhong = 3;
            }
            String ma = txtMa.getText();
            String diaChi = txtDiaChi.getText();
            String quan = txtQuan.getText();
            String thanhPho = (String) cbxThanhPho.getSelectedItem();
            String loai = (String) cbxLoai.getSelectedItem();
            int dien = Integer.valueOf(txtDienTich.getText());
            int gia = Integer.valueOf(txtGia.getText());
            BatDongSan bds = new BatDongSan(0, chu, vanPhong, ma, diaChi, quan, thanhPho, loai, dien, gia);
            boolean check = service.updateById(ma, bds);
            if (check) {
                showData(listBatDongSan = service.getData());
                JOptionPane.showMessageDialog(this, "Sửa Thành Công");
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Thất bại");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    public void loadListBDS() {
        listLoaiBDS = new ArrayList<>();
        cbxLoai.setModel(dcbm = new DefaultComboBoxModel());
        listLoaiBDS.add("Đất thổ cư");
        listLoaiBDS.add("Đất nông nghiệp");
        listLoaiBDS.add("Đất lâm nghiệp");
        listLoaiBDS.add("Đất quy hoạch");
        dcbm.addAll(listLoaiBDS);
        cbxLoai.setSelectedIndex(0);
    }

    public void loadCSH() {
        listCSH = new ArrayList<>();
        cbxChuSoHuu.setModel(dcbm = new DefaultComboBoxModel());
        listCSH.add("Nguyễn Thanh Đức");
        listCSH.add("Nguyễn Thanh Tuấn");
        listCSH.add("Nguyễn Thanh Hiệu");
        listCSH.add("Nguyễn Thanh Nam");
        listCSH.add("Nguyễn Thanh Tùng");
        dcbm.addAll(listCSH);
        cbxChuSoHuu.setSelectedIndex(0);
    }

    public void loadVP() {
        listVP = new ArrayList();
        cbxVanPhong.setModel(dcbm = new DefaultComboBoxModel());
        listVP.add("Bất động sản Thành Hưng");
        listVP.add("Bất động sản Nam Hưng");
        listVP.add("Bất động sản Tuấn hưng");
        dcbm.addAll(listVP);
        cbxVanPhong.setSelectedIndex(0);
    }

    public void loadTP() {
        listTP = new ArrayList<>();
        cbxThanhPho.setModel(dcbm = new DefaultComboBoxModel());
        listTP.add("Hà Nội");
        listTP.add("Hồ Chí Minh");
        dcbm.addAll(listTP);
        cbxThanhPho.setSelectedIndex(0);
    }

    public void loadSort() {
        listSort = new ArrayList<>();
        cbxSapXep.setModel(dcbm = new DefaultComboBoxModel());
        listSort.add("Mã");
        listSort.add("Giá tiền");
        listSort.add("Diện tích");
        dcbm.addAll(listSort);
        cbxSapXep.setSelectedIndex(0);
    }

    public void loadChieu() {
        listChieu = new ArrayList<>();
        cbxChieu.setModel(dcbm = new DefaultComboBoxModel());
        listChieu.add("tăng");
        listChieu.add("giảm");
        dcbm.addAll(listChieu);
        cbxChieu.setSelectedIndex(0);
    }

    public void showData(List<BatDongSan> list) {
        dtm.setRowCount(0);
        list.forEach(s -> dtm.addRow(s.toshowData()));
    }

    public void fill(int index) {
        BatDongSan bs = listBatDongSan.get(index);
        String check = "";
        if (bs.getChuSoHuu() == 1) {
            check = "Nguyễn Thanh Đức";
        } else if (bs.getChuSoHuu() == 2) {
            check = "Nguyễn Thanh Tuấn";
        } else if (bs.getChuSoHuu() == 3) {
            check = "Nguyễn Thanh Hiệu";
        } else if (bs.getChuSoHuu() == 4) {
            check = "Nguyễn Thanh Nam";
        } else {
            check = "Nguyễn Thanh Tùng";
        }
        String check1 = "";
        if (bs.getVanPhong() == 1) {
            check1 = "Bất động sản Thành Hưng";
        } else if (bs.getVanPhong() == 2) {
            check1 = "Bất động sản Nam Hưng";
        } else {
            check1 = "Bất động sản Tuấn Hưng";
        }
        txtMa.setText(bs.getMa());
        txtDiaChi.setText(bs.getDiaChi());
        txtDienTich.setText(bs.getDienTich() + "");
        txtQuan.setText(bs.getQuan());
        cbxLoai.setSelectedItem(bs.getLoai());
        cbxChuSoHuu.setSelectedItem(check);
        cbxVanPhong.setSelectedItem(check1);
        cbxThanhPho.setSelectedItem(bs.getThanhPho());
        txtGia.setText(bs.getGia() + "");
    }

    public boolean myValidate() {
        boolean flag = false;
        int chon = 0;
        for (int i = 0; i < listBatDongSan.size(); i++) {
            if (listBatDongSan.get(i).equals(txtMa)) {
                chon++;
            }
        }
        if (txtMa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (txtQuan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (txtDiaChi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (txtDienTich.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (txtGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "không được để trống bất kỳ trường nào");
        } else if (!txtGia.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(rootPane, "giá và diện tích phải là số");
        } else if (!txtDienTich.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(rootPane, "giá và diện tích phải là số");
        } else if (chon > 0) {
            JOptionPane.showMessageDialog(rootPane, "không được nhập trùng mã");
        } else {
            flag = true;
        }
        return flag;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyBDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyBDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyBDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyBDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuanLyBDS().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxChieu;
    private javax.swing.JComboBox<String> cbxChuSoHuu;
    private javax.swing.JComboBox<String> cbxLoai;
    private javax.swing.JComboBox<String> cbxSapXep;
    private javax.swing.JComboBox<String> cbxThanhPho;
    private javax.swing.JComboBox<String> cbxVanPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHienThi;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtDienTich;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtQuan;
    // End of variables declaration//GEN-END:variables
}
